apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: blitzy-iTerm2
  description: iTerm2 is a terminal emulator for Mac OS X that does amazing things.
  tags: []
  annotations:
    github.com/project-slug: Blitzy-Sandbox/blitzy-iTerm2
    backstage.io/source-location: url:https://github.com/Blitzy-Sandbox/blitzy-iTerm2/tree/master/
    backstage.io/techdocs-ref: dir:.
spec:
  type: tool
  lifecycle: production
  owner: blitzy-sandbox
  system: blitzy-sandbox-projects
